/**
 * MOCK DATA — NOT LIVE BETTING DATA. NOT BETTING ADVICE.
 * All player names, lines, odds, and projections are fictional examples
 * used for development and demonstration only. Do not use for wagering decisions.
 */

import type { BetCandidate, BetDecision, AppSettings, BankrollState, PerformanceSummary } from '../types'

const now = new Date()
const todayAt = (h: number, m = 0) => {
  const d = new Date(now)
  d.setHours(h, m, 0, 0)
  return d.toISOString()
}

// ─── Mock Candidates ──────────────────────────────────────────────────────────
// 12 NBA player prop candidates with varying system scores.
// Statuses: candidate (pending review), watchlist, rejected.

export const MOCK_CANDIDATES: BetCandidate[] = [
  // ── Score 8.5 — Candidate (should reach approval queue) ─────────────────
  {
    id: 'cand-001',
    sport: 'Basketball',
    league: 'NBA',
    game: 'NYK vs BOS',
    game_start_time: todayAt(19, 30),
    market: 'Player Points',
    player_or_team: 'Marcus Webb',
    bet_type: 'Over',
    line: 22.5,
    odds: -110,
    sportsbook: 'FanDuel',
    projection: 25.1,
    projection_edge: 2.6,
    implied_probability: 52.38,
    projected_probability: 56.2,
    estimated_ev: 0.072,
    system_score: 8.5,
    confidence_tier: 'Medium',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Minutes stable over last 5 games (34.2 avg)',
      'Opponent allows 3rd-highest guard scoring in last 10 games',
      'Usage rate increased with primary playmaker questionable',
    ],
    risk_flags: [],
    market_comparison: [
      { sportsbook: 'FanDuel',    line: 22.5, odds: -110 },
      { sportsbook: 'DraftKings', line: 23.5, odds: -115 },
      { sportsbook: 'BetMGM',     line: 23.5, odds: -110 },
      { sportsbook: 'Caesars',    line: 23.0, odds: -112 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(10, 15),
    updated_at: todayAt(10, 15),
  },

  // ── Score 9.1 — High confidence candidate ────────────────────────────────
  {
    id: 'cand-002',
    sport: 'Basketball',
    league: 'NBA',
    game: 'LAL vs GSW',
    game_start_time: todayAt(20, 0),
    market: 'Player Rebounds',
    player_or_team: 'Devon Okafor',
    bet_type: 'Over',
    line: 9.5,
    odds: -108,
    sportsbook: 'DraftKings',
    projection: 12.1,
    projection_edge: 2.6,
    implied_probability: 51.92,
    projected_probability: 57.8,
    estimated_ev: 0.114,
    system_score: 9.1,
    confidence_tier: 'High',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Opponent ranks 29th in rebounding defense last 15 games',
      'Starting center for opponent is listed as probable but limited',
      'Averaging 11.4 rebounds over last 8 games',
      'Game pace projects as top-3 this week',
    ],
    risk_flags: [],
    market_comparison: [
      { sportsbook: 'DraftKings', line: 9.5,  odds: -108 },
      { sportsbook: 'FanDuel',    line: 10.5, odds: -110 },
      { sportsbook: 'PointsBet',  line: 10.5, odds: -112 },
      { sportsbook: 'BetMGM',     line: 10.0, odds: -115 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(9, 45),
    updated_at: todayAt(11, 0),
  },

  // ── Score 8.2 — Candidate ────────────────────────────────────────────────
  {
    id: 'cand-003',
    sport: 'Basketball',
    league: 'NBA',
    game: 'MIA vs CHI',
    game_start_time: todayAt(19, 0),
    market: 'Player Assists',
    player_or_team: 'Jaylen Croft',
    bet_type: 'Over',
    line: 6.5,
    odds: -112,
    sportsbook: 'Caesars',
    projection: 8.2,
    projection_edge: 1.7,
    implied_probability: 52.83,
    projected_probability: 57.4,
    estimated_ev: 0.085,
    system_score: 8.2,
    confidence_tier: 'Medium',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Ball-handling load increased after trade deadline move',
      'Miami opponent allows 4th-most assists per game to opposing PG',
      'Teammate with high usage questionable',
    ],
    risk_flags: ['Teammate questionable — may return and reduce usage'],
    market_comparison: [
      { sportsbook: 'Caesars',    line: 6.5, odds: -112 },
      { sportsbook: 'FanDuel',    line: 7.5, odds: -110 },
      { sportsbook: 'DraftKings', line: 7.5, odds: -115 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(10, 30),
    updated_at: todayAt(10, 30),
  },

  // ── Score 8.8 — High confidence candidate ────────────────────────────────
  {
    id: 'cand-004',
    sport: 'Basketball',
    league: 'NBA',
    game: 'PHX vs DEN',
    game_start_time: todayAt(21, 0),
    market: 'Player PRA',
    player_or_team: 'Tomas Guerrero',
    bet_type: 'Over',
    line: 37.5,
    odds: -115,
    sportsbook: 'FanDuel',
    projection: 41.8,
    projection_edge: 4.3,
    implied_probability: 53.49,
    projected_probability: 59.1,
    estimated_ev: 0.098,
    system_score: 8.8,
    confidence_tier: 'High',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Averaging 41.2 PRA over last 10 games',
      'Denver defensive scheme leaves wing forwards open in transition',
      'Rest advantage — 2 days vs. back-to-back for opponent',
      'Line lowest across all major books by 2+ points',
    ],
    risk_flags: [],
    market_comparison: [
      { sportsbook: 'FanDuel',    line: 37.5, odds: -115 },
      { sportsbook: 'DraftKings', line: 39.5, odds: -110 },
      { sportsbook: 'BetMGM',     line: 39.5, odds: -112 },
      { sportsbook: 'Caesars',    line: 38.5, odds: -118 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(8, 0),
    updated_at: todayAt(11, 30),
  },

  // ── Score 7.2 — Watchlist ────────────────────────────────────────────────
  {
    id: 'cand-005',
    sport: 'Basketball',
    league: 'NBA',
    game: 'ATL vs TOR',
    game_start_time: todayAt(18, 30),
    market: 'Player Threes',
    player_or_team: 'Andre Simmons',
    bet_type: 'Over',
    line: 2.5,
    odds: -120,
    sportsbook: 'BetMGM',
    projection: 3.1,
    projection_edge: 0.6,
    implied_probability: 54.55,
    projected_probability: 58.0,
    estimated_ev: 0.028,
    system_score: 7.2,
    confidence_tier: 'Low',
    recommended_action: 'Watch',
    max_units: 1,
    context_notes: [
      'Shooting 41% from three over last 6 games',
      'Toronto opponent ranks 25th in three-point defense',
    ],
    risk_flags: [
      'Odds near caution threshold (-120)',
      'Edge below preferred minimum on this market',
    ],
    market_comparison: [
      { sportsbook: 'BetMGM',     line: 2.5, odds: -120 },
      { sportsbook: 'FanDuel',    line: 2.5, odds: -118 },
      { sportsbook: 'DraftKings', line: 3.5, odds: +102 },
    ],
    rule_checklist: {
      projection_edge: 'warn',
      odds_value: 'warn',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'watchlist',
    created_at: todayAt(9, 0),
    updated_at: todayAt(9, 0),
  },

  // ── Score 6.8 — Watchlist ────────────────────────────────────────────────
  {
    id: 'cand-006',
    sport: 'Basketball',
    league: 'NBA',
    game: 'SAS vs OKC',
    game_start_time: todayAt(20, 30),
    market: 'Player Points',
    player_or_team: 'Elijah Monroe',
    bet_type: 'Over',
    line: 18.5,
    odds: -118,
    sportsbook: 'Caesars',
    projection: 20.4,
    projection_edge: 1.9,
    implied_probability: 54.13,
    projected_probability: 57.2,
    estimated_ev: 0.041,
    system_score: 6.8,
    confidence_tier: 'Low',
    recommended_action: 'Watch',
    max_units: 1,
    context_notes: [
      'Usage trending up over last 4 games',
      'OKC opponent weak against SF position historically',
    ],
    risk_flags: [
      'Injury report not yet updated for this game',
      'Line has moved 0.5 points already today',
    ],
    market_comparison: [
      { sportsbook: 'Caesars',    line: 18.5, odds: -118 },
      { sportsbook: 'FanDuel',    line: 19.0, odds: -112 },
      { sportsbook: 'DraftKings', line: 19.0, odds: -110 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'warn',
      context: 'warn',
      market_confirmation: 'warn',
      bankroll: 'pass',
    },
    status: 'watchlist',
    created_at: todayAt(11, 0),
    updated_at: todayAt(11, 0),
  },

  // ── Score 4.2 — Auto-rejected (odds) ────────────────────────────────────
  {
    id: 'cand-007',
    sport: 'Basketball',
    league: 'NBA',
    game: 'CLE vs MIL',
    game_start_time: todayAt(19, 30),
    market: 'Player Points',
    player_or_team: 'Grant Holloway',
    bet_type: 'Over',
    line: 24.5,
    odds: -140,
    sportsbook: 'BetMGM',
    projection: 26.1,
    projection_edge: 1.6,
    implied_probability: 58.33,
    projected_probability: 58.8,
    estimated_ev: -0.008,
    system_score: 4.2,
    confidence_tier: 'Low',
    recommended_action: 'Reject',
    max_units: 0,
    context_notes: [
      'Strong role — averaging 36 minutes per game',
    ],
    risk_flags: [
      'Odds exceed hard stop (-130 threshold)',
      'Negative estimated EV at current juice level',
      'Edge too small to overcome juice',
    ],
    market_comparison: [
      { sportsbook: 'BetMGM',     line: 24.5, odds: -140 },
      { sportsbook: 'FanDuel',    line: 24.5, odds: -135 },
      { sportsbook: 'DraftKings', line: 24.5, odds: -132 },
    ],
    rule_checklist: {
      projection_edge: 'warn',
      odds_value: 'fail',
      context: 'warn',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'rejected',
    created_at: todayAt(9, 30),
    updated_at: todayAt(9, 30),
  },

  // ── Score 3.1 — Rejected (questionable) ─────────────────────────────────
  {
    id: 'cand-008',
    sport: 'Basketball',
    league: 'NBA',
    game: 'IND vs WAS',
    game_start_time: todayAt(18, 0),
    market: 'Player Rebounds',
    player_or_team: 'Chris Baxter',
    bet_type: 'Over',
    line: 7.5,
    odds: -110,
    sportsbook: 'FanDuel',
    projection: 9.1,
    projection_edge: 1.6,
    implied_probability: 52.38,
    projected_probability: 56.4,
    estimated_ev: 0.075,
    system_score: 3.1,
    confidence_tier: 'Low',
    recommended_action: 'Reject',
    max_units: 0,
    context_notes: [],
    risk_flags: [
      'Player listed questionable — ankle — minutes unknown',
      'Minutes restriction possible per beat reporter',
      'Projection assumes full minutes — invalid if limited',
    ],
    market_comparison: [
      { sportsbook: 'FanDuel',    line: 7.5, odds: -110 },
      { sportsbook: 'DraftKings', line: 7.5, odds: -112 },
    ],
    rule_checklist: {
      projection_edge: 'warn',
      odds_value: 'pass',
      context: 'fail',
      market_confirmation: 'warn',
      bankroll: 'pass',
    },
    status: 'rejected',
    created_at: todayAt(10, 0),
    updated_at: todayAt(10, 0),
  },

  // ── Score 8.0 — Candidate ────────────────────────────────────────────────
  {
    id: 'cand-009',
    sport: 'Basketball',
    league: 'NBA',
    game: 'MIN vs POR',
    game_start_time: todayAt(21, 30),
    market: 'Player Points',
    player_or_team: 'Khalil Davis',
    bet_type: 'Over',
    line: 15.5,
    odds: -110,
    sportsbook: 'DraftKings',
    projection: 18.0,
    projection_edge: 2.5,
    implied_probability: 52.38,
    projected_probability: 56.8,
    estimated_ev: 0.082,
    system_score: 8.0,
    confidence_tier: 'Medium',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Portland defense allowing elevated scoring to off-guards',
      'Starting role confirmed — averaged 34 min last 7 games',
      'Pace projection is top-5 for this slate',
    ],
    risk_flags: [],
    market_comparison: [
      { sportsbook: 'DraftKings', line: 15.5, odds: -110 },
      { sportsbook: 'FanDuel',    line: 16.5, odds: -110 },
      { sportsbook: 'Caesars',    line: 16.0, odds: -108 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(8, 30),
    updated_at: todayAt(8, 30),
  },

  // ── Score 7.5 — Watchlist ────────────────────────────────────────────────
  {
    id: 'cand-010',
    sport: 'Basketball',
    league: 'NBA',
    game: 'DET vs HOU',
    game_start_time: todayAt(20, 0),
    market: 'Player Assists',
    player_or_team: 'Ricky Fontaine',
    bet_type: 'Over',
    line: 8.5,
    odds: -115,
    sportsbook: 'PointsBet',
    projection: 10.1,
    projection_edge: 1.6,
    implied_probability: 53.49,
    projected_probability: 58.1,
    estimated_ev: 0.069,
    system_score: 7.5,
    confidence_tier: 'Medium',
    recommended_action: 'Watch',
    max_units: 1,
    context_notes: [
      'High-assist role confirmed after starter injury',
      'Houston opponent ranks bottom-5 in assist differential allowed',
    ],
    risk_flags: [
      'Waiting for final injury report — starter may return',
    ],
    market_comparison: [
      { sportsbook: 'PointsBet',  line: 8.5, odds: -115 },
      { sportsbook: 'FanDuel',    line: 9.5, odds: -110 },
      { sportsbook: 'DraftKings', line: 9.5, odds: -112 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'watchlist',
    created_at: todayAt(10, 45),
    updated_at: todayAt(10, 45),
  },

  // ── Score 8.4 — Candidate ────────────────────────────────────────────────
  {
    id: 'cand-011',
    sport: 'Basketball',
    league: 'NBA',
    game: 'UTA vs SAC',
    game_start_time: todayAt(21, 0),
    market: 'Player Threes',
    player_or_team: 'Felix Okonkwo',
    bet_type: 'Over',
    line: 1.5,
    odds: -108,
    sportsbook: 'Caesars',
    projection: 2.4,
    projection_edge: 0.9,
    implied_probability: 51.92,
    projected_probability: 57.5,
    estimated_ev: 0.103,
    system_score: 8.4,
    confidence_tier: 'Medium',
    recommended_action: 'Manual Review',
    max_units: 1,
    context_notes: [
      'Averaging 2.3 threes per game over last 12 games',
      'Sacramento ranks 28th in three-point defense',
      'Minutes stable at 32 avg — no injury concerns',
    ],
    risk_flags: [],
    market_comparison: [
      { sportsbook: 'Caesars',    line: 1.5, odds: -108 },
      { sportsbook: 'FanDuel',    line: 1.5, odds: -115 },
      { sportsbook: 'DraftKings', line: 2.5, odds: +105 },
      { sportsbook: 'BetMGM',     line: 1.5, odds: -118 },
    ],
    rule_checklist: {
      projection_edge: 'pass',
      odds_value: 'pass',
      context: 'pass',
      market_confirmation: 'pass',
      bankroll: 'pass',
    },
    status: 'candidate',
    created_at: todayAt(9, 15),
    updated_at: todayAt(9, 15),
  },

  // ── Score 2.8 — Rejected (negative EV, blowout risk) ─────────────────────
  {
    id: 'cand-012',
    sport: 'Basketball',
    league: 'NBA',
    game: 'CHA vs BOS',
    game_start_time: todayAt(19, 30),
    market: 'Player Points',
    player_or_team: 'Ray Sullivan',
    bet_type: 'Over',
    line: 20.5,
    odds: -128,
    sportsbook: 'BetMGM',
    projection: 21.8,
    projection_edge: 1.3,
    implied_probability: 56.14,
    projected_probability: 55.9,
    estimated_ev: -0.019,
    system_score: 2.8,
    confidence_tier: 'Low',
    recommended_action: 'Reject',
    max_units: 0,
    context_notes: [
      'Role is confirmed on paper',
    ],
    risk_flags: [
      'Boston projected 18-point favorite — blowout risk',
      'Negative estimated EV at current price',
      'Minutes may be pulled if blowout occurs in Q3',
      'Juice near hard stop',
    ],
    market_comparison: [
      { sportsbook: 'BetMGM',     line: 20.5, odds: -128 },
      { sportsbook: 'FanDuel',    line: 20.5, odds: -125 },
    ],
    rule_checklist: {
      projection_edge: 'warn',
      odds_value: 'fail',
      context: 'warn',
      market_confirmation: 'warn',
      bankroll: 'pass',
    },
    status: 'rejected',
    created_at: todayAt(11, 0),
    updated_at: todayAt(11, 0),
  },
]

// ─── Mock decisions (past resolved bets for performance page) ─────────────────

export const MOCK_DECISIONS: BetDecision[] = [
  {
    id: 'dec-001',
    candidate_id: 'hist-001',
    decision: 'approve',
    decision_reason: 'Strong projection edge + market confirmation',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6).toISOString(),
    original_line: 21.5,
    original_odds: -110,
    closing_line: 22.5,
    closing_odds: -118,
    result: 'win',
    profit_loss_units: 0.91,
    notes: 'Line moved in our favor. Good CLV.',
  },
  {
    id: 'dec-002',
    candidate_id: 'hist-002',
    decision: 'approve',
    decision_reason: 'High score, no risk flags',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(),
    original_line: 9.5,
    original_odds: -112,
    closing_line: 10.5,
    closing_odds: -115,
    result: 'win',
    profit_loss_units: 0.89,
  },
  {
    id: 'dec-003',
    candidate_id: 'hist-003',
    decision: 'approve',
    decision_reason: 'Solid context, line advantage',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(),
    original_line: 7.5,
    original_odds: -108,
    closing_line: 7.5,
    closing_odds: -110,
    result: 'loss',
    profit_loss_units: -1.0,
  },
  {
    id: 'dec-004',
    candidate_id: 'hist-004',
    decision: 'approve',
    decision_reason: 'Strong score + opponent weakness confirmed',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4).toISOString(),
    original_line: 37.5,
    original_odds: -110,
    closing_line: 39.5,
    closing_odds: -120,
    result: 'win',
    profit_loss_units: 0.91,
    notes: 'Excellent CLV — line moved 2 points in our favor.',
  },
  {
    id: 'dec-005',
    candidate_id: 'hist-005',
    decision: 'approve',
    decision_reason: 'High system score — clear market discrepancy',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3).toISOString(),
    original_line: 24.5,
    original_odds: -110,
    closing_line: 25.5,
    closing_odds: -115,
    result: 'win',
    profit_loss_units: 0.91,
  },
  {
    id: 'dec-006',
    candidate_id: 'hist-006',
    decision: 'approve',
    decision_reason: 'Projection edge + rest advantage',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(),
    original_line: 16.5,
    original_odds: -112,
    closing_line: 16.5,
    closing_odds: -112,
    result: 'loss',
    profit_loss_units: -1.0,
  },
  {
    id: 'dec-007',
    candidate_id: 'hist-007',
    decision: 'approve',
    decision_reason: 'Score 8.4 — passed all filters',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(),
    original_line: 1.5,
    original_odds: -108,
    closing_line: 1.5,
    closing_odds: -115,
    result: 'win',
    profit_loss_units: 0.93,
  },
  {
    id: 'dec-008',
    candidate_id: 'hist-008',
    decision: 'approve',
    decision_reason: 'Strong edge across all filters',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(),
    original_line: 14.5,
    original_odds: -110,
    closing_line: 15.5,
    closing_odds: -118,
    result: 'push',
    profit_loss_units: 0,
  },
  {
    id: 'dec-009',
    candidate_id: 'hist-009',
    decision: 'approve',
    decision_reason: 'High probability edge + clean injury report',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(),
    original_line: 8.5,
    original_odds: -110,
    closing_line: 9.5,
    closing_odds: -112,
    result: 'win',
    profit_loss_units: 0.91,
  },
  {
    id: 'dec-010',
    candidate_id: 'hist-010',
    decision: 'approve',
    decision_reason: 'Stale line — book behind market',
    approved_units: 1,
    timestamp: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
    original_line: 22.5,
    original_odds: -108,
    closing_line: 22.5,
    closing_odds: -118,
    result: 'pending',
    profit_loss_units: undefined,
  },
]

// ─── Default settings ────────────────────────────────────────────────────────

export const DEFAULT_SETTINGS: AppSettings = {
  bankroll: 5000,
  unit_percentage: 1,
  max_daily_units: 3,
  max_weekly_units: 10,
  daily_stop_loss_units: -3,
  minimum_score: 8,
  minimum_probability_edge: 3,
  max_juice_warning: -120,
  max_juice_hard_stop: -130,
  parlays_enabled: false,
  allowed_markets: [
    'Player Points',
    'Player Rebounds',
    'Player Assists',
    'Player PRA',
    'Player Threes',
    'Player Blocks',
    'Player Steals',
    'Game Total',
  ],
  banned_markets: [],
}

// ─── Default bankroll state ──────────────────────────────────────────────────

export const DEFAULT_BANKROLL: BankrollState = {
  starting_bankroll: 5000,
  current_bankroll: 5045,
  unit_size: 50,
  daily_units_used: 1,
  weekly_units_used: 4,
  daily_units_won_lost: 0.91,
  open_risk_units: 1,
  stop_loss_triggered: false,
  daily_exposure_limit_reached: false,
}

// ─── Mock performance summary ─────────────────────────────────────────────────

export const MOCK_PERFORMANCE: PerformanceSummary = {
  total_approved: 10,
  total_wins: 6,
  total_losses: 2,
  total_pushes: 1,
  total_pending: 1,
  units_won: 5.56,
  units_lost: 2.0,
  net_units: 3.56,
  roi: 35.6,
  clv_hit_rate: 70,
  win_rate: 66.7,
  avg_edge: 7.8,
  avg_closing_line_movement: 0.8,
  bets_by_sport: {
    Basketball: { count: 10, wins: 6, net_units: 3.56, avg_edge: 7.8 },
  },
  bets_by_market: {
    'Player Points':   { count: 4, wins: 3, net_units: 1.73 },
    'Player Rebounds': { count: 2, wins: 2, net_units: 1.80 },
    'Player Assists':  { count: 2, wins: 1, net_units: -0.09 },
    'Player Threes':   { count: 1, wins: 1, net_units: 0.93 },
    'Player PRA':      { count: 1, wins: 1, net_units: 0.91 },
  },
  bets_by_sportsbook: {
    FanDuel:    { count: 4, net_units: 1.82 },
    DraftKings: { count: 3, net_units: 1.71 },
    Caesars:    { count: 2, net_units: 0.03 },
    PointsBet:  { count: 1, net_units: 0.00 },
  },
  rejection_reasons: [
    { reason: 'Odds exceed hard stop', count: 5 },
    { reason: 'Player questionable', count: 4 },
    { reason: 'Negative estimated EV', count: 3 },
    { reason: 'Projection edge below threshold', count: 3 },
    { reason: 'Blowout risk flagged', count: 2 },
    { reason: 'Injury/news data stale', count: 2 },
  ],
  bad_bets: [],
  timeline: [
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6).toISOString(), cumulative_units: 0.91, bets: 1 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(), cumulative_units: 1.80, bets: 2 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4).toISOString(), cumulative_units: 2.71, bets: 1 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3).toISOString(), cumulative_units: 3.62, bets: 1 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(), cumulative_units: 3.55, bets: 2 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(), cumulative_units: 4.46, bets: 2 },
    { date: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),      cumulative_units: 4.46, bets: 1 },
  ],
}
